---
title: "Activity Monitor Data"
author: "Avinash Bhura"
date: "September 16, 2015"
output: html_document
---
Loading and preprocessing the data located on file: "activity.csv" into R 

```{r}
adata<-read.csv("activity.csv")
data<-adata
```

What is mean total number of steps taken per day?

```{r, echo=TRUE}
## Removing NA's
data<-data[complete.cases(data),]
##1.Calculate the total number of steps taken per day

library(sqldf)
nsteps<-sqldf("select count(steps) step,date from data group by date")
## Make a histogram of the total number of steps taken each day
hist(nsteps$step)

##Calculate and report the mean and median of the total number of steps taken per day

library(plyr)
avg<-ddply(data,~date,summarise,mean=mean(steps),median=median(steps))
avg
##time series plot
plot(avg$mean,avg$date,type = "l",axes = avg$mean)
axis(1,at = c(1:20)*5)

##2.Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
data[which.max(data[,"steps"]),"interval"]

##Imputing missing values

##1.Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
nrow(adata[is.na(adata$steps),])

## The  strategy is filling the missing values in the dataset with mean

navg<-ddply(adata,~date,summarise,mean=mean(steps))
navg[is.na(navg$mean),"mean"]<- c(0)

fdata<-sqldf("select adata.*,navg.mean from adata inner join navg on adata.date=navg.date")

## New data set is fdata
fdata[is.na(fdata[,"steps"]),"steps"]<- fdata[is.na(fdata[,"steps"]),"mean"]
fdata<-fdata[,1:3]

navg<-ddply(fdata,~date,summarise,mean=mean(steps),median=median(steps))

hist(navg$mean)

hist(navg$median)

```

